# Generated by Django 3.2.9 on 2021-12-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
